apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=true,SelfHeal=true
    argocd.argoproj.io/refresh: hard
    config-revision: 1fc4b0a04ec86c5a71b4e79b27c19a15b1cf8fd8
spec:
  project: subride
  source:
    repoURL: https://github.com/cna-bootcamp/argo-manifests.git
    targetRevision: main
    path: charts/stable/subride
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/cna-bootcamp/argo-manifests/main/config/config.yaml?ref=1fc4b0a04ec86c5a71b4e79b27c19a15b1cf8fd8
  destination:
    server: https://kubernetes.default.svc
    namespace: gappa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
