apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=true,SelfHeal=true
    argocd.argoproj.io/refresh: hard
    config-revision: 7a00e93e5756116983fb25466e371b23b2ca6633
spec:
  project: subride
  source:
    repoURL: https://github.com/cna-bootcamp/argo-manifests.git
    targetRevision: main
    path: charts/stable/subride
    helm:
      valueFiles:
      - ["../../../config/config.yaml"]
  destination:
    server: https://kubernetes.default.svc
    namespace: gappa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
