apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=true,SelfHeal=true
    argocd.argoproj.io/refresh: hard
    config-revision: 0878e7ff835d8e375b2daf4a9b8c3225f786fc9f
spec:
  project: subride
  source:
    repoURL: https://raw.githubusercontent.com/cna-bootcamp/helm-charts/main/stable
    targetRevision: 1.0.4
    chart: subride
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/cna-bootcamp/argo-manifests/main/config/config.yaml?ref=0878e7ff835d8e375b2daf4a9b8c3225f786fc9f
  destination:
    server: https://kubernetes.default.svc
    namespace: gappa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
